apiVersion: teddy.io/v1
kind: Email
metadata:
  name: test-email-1
spec:
  senderConfigRef: mailersend-config
  recipientEmail: recipient1@example.com
  subject: "Test Email 1"
  body: "This is a test email sent via the Kubernetes Email Operator."