apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-operator-role
rules:
  - apiGroups: ["teddy.io"]
    resources: ["emailsenderconfigs", "emails"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get","create", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]