{{- range .Values.providers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-token-secret
  namespace: {{ $.Values.operator.namespace }}
type: Opaque
data:
  apiToken: {{ .apiToken }}
---
{{- end }}
