apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.teddy.io
spec:
  group: teddy.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiTokenSecretRef:
                  type: string
                senderEmail:
                  type: string
  scope: Namespaced
  names:
    plural: emailsenderconfigs
    singular: emailsenderconfig
    kind: EmailSenderConfig
    shortNames:
      - esc
